apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mako.fullname" . }}-config
  labels:
    {{- include "mako.labels" . | nindent 4 }}
data:
  pipeline.yaml: |
    {{- .Values.pipeline.config | nindent 4 }}
